<!DOCTYPE html>
<html>
<head>
    <title><?php echo $title ?></title>
    <script
           src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="assets/js/shopping_list.js<?php echo '?'.mt_rand(); ?>"></script>
    
    <?php
        foreach ($style as $sheet) {
            echo "<link rel='stylesheet' type='text/css' href='assets/css/$sheet'>";
        }
        /*
        foreach ($scripts as $script) {
            echo "<script type='text/javascript' src='assets/js/$script'></script>";
        }
        */

    ?>
</head>
<body>
<div class="container">